### PR TITLE
CreateCollab Extensions

### LINKED ISSUE #33: DB#CreateCollab Extensions
As a follow-up to the changes made in #32, we should futureproof and extend the interface with a way to create a session with a specific name, failing if the session already exists. This would be a good feature for teachers who want to keep their collaborative session IDs readable. For example:

```
POST .../collab/create
{
    "name": "my session", // Optional field, defaults to random UUID.
    "uid": "..."
}
```

Then, the response would be `201 Created` if the session was created with the name, and `400 Bad Request` if the request failed (and the session already existed).

### PR DESCRIPTION
**Pull request by joshSi**
Add name field and returns `400 Bad Request` if a session with that name exists.

Closes #33.

### CODE REVIEW

File: db/collab.go [hunk 1]
```diff
@@ -67,15 +67,32 @@ func (s *Session) Broadcast(msg Message) error {
 	return mostRecentError
 }
 
+// CreateCollab creates a collaborative session, setting up the session's websocket.
+// Request Body:
+// {
+//    uid: UID for the user the program belongs to
+//	  name: optional name identifier for the session, defaults to random UUID.
+// }
```
Comment (krashanoff) [inline db/collab.go:75]:
```suggestion
// Request Body:
// {
//    uid: UID for the user the program belongs to
//    name: optional name identifier for the session, defaults to random UUID.
// }
```

**Review by krashanoff — APPROVED** [review]
Josh, thanks for tackling this change. Things look good to merge. I did leave one tiny nitpicky suggestion though.

I'll assign you your next card soon. It will likely be laying the foundations for the websockets message passing interface :+1:
